# Generated by Django 6.0.7 on 2026-07-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
