# Generated by Django 6.0.7 on 2026-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0002_warehouse_workers_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
