# Generated by Django 6.0.7 on 2026-07-21 16:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0003_alter_worker_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier_sku', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'material supplier',
                'verbose_name_plural': 'material suppliers',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'stock balance',
                'verbose_name_plural': 'stock balances',
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='material',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='material',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='material',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='material',
            name='species',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='thickness_mm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('m', 'Meters'), ('m2', 'Square Meters'), ('m3', 'Cubic Meters')], default='pcs', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='width_mm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='material_sale_price_non_negative'),
        ),
        migrations.AddField(
            model_name='materialsupplier',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offers', to='lumberyard.material'),
        ),
        migrations.AddField(
            model_name='materialsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_offers', to='lumberyard.supplier'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='lumberyard.material'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='lumberyard.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='materialsupplier',
            constraint=models.UniqueConstraint(fields=('material', 'supplier'), name='unique_material_supplier_offer'),
        ),
        migrations.AddConstraint(
            model_name='materialsupplier',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='supplier_purchase_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('material', 'warehouse'), name='unique_material_warehouse_stock'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_non_negative'),
        ),
    ]
