# Generated by Django 6.0.7 on 2026-07-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0003_supplier_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'warehouse', 'verbose_name_plural': 'warehouses'},
        ),
    ]
