# Generated by Django 6.0.7 on 2026-07-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0004_alter_supplier_options_alter_warehouse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
