# Generated by Django 6.0.7 on 2026-07-23 09:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0004_materialsupplier_stockbalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
