# Generated by Django 6.0.7 on 2026-07-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0005_alter_worker_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='workers',
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='replenishment_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='replenishment_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_replenishments', to=settings.AUTH_USER_MODEL),
        ),
    ]
