from django.urls import include, path

from . import views

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path(
        "materials/",
        views.MaterialListView.as_view(),
        name="material-list",
    ),
    path(
        "materials/<int:pk>/",
        views.MaterialDetailView.as_view(),
        name="material-detail",
    ),
    path(
        "materials/create/",
        views.MaterialCreateView.as_view(),
        name="material-create"
    ),
    path(
        "materials/<int:pk>/update/",
        views.MaterialUpdateView.as_view(),
        name="material-update",
    ),
    path(
        "materials/<int:pk>/delete/",
        views.MaterialDeleteView.as_view(),
        name="material-delete",
    ),
    path(
        "workers/",
        views.WorkerListView.as_view(),
        name="worker-list",
    ),
    path(
        "workers/create/",
        views.WorkerCreateView.as_view(),
        name="worker-create",
    ),
    path(
        "workers/<int:pk>/delete/",
        views.WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "materials/<int:pk>/stock/<int:stock_pk>/toggle-replenishment/",
        views.toggle_replenishment,
        name="material-toggle-replenishment",
    ),
    path(
        "replenishment/",
        views.ReplenishmentListView.as_view(),
        name="replenishment-list",
    ),
    path(
        "materials/<int:material_pk>/stock/<int:warehouse_pk>/update/",
        views.stockbalance_update,
        name="stockbalance-update",
    ),
    path(
        "suppliers/",
        views.SupplierListView.as_view(),
        name="supplier-list"
    ),
    path(
        "suppliers/create/",
        views.SupplierCreateView.as_view(),
        name="supplier-create"
    ),
    path(
        "suppliers/<int:pk>/update/",
        views.SupplierUpdateView.as_view(),
        name="supplier-update"
    ),
    path(
        "suppliers/<int:pk>/delete/",
        views.SupplierDeleteView.as_view(),
        name="supplier-delete"
    ),
    path(
        "categories/",
        views.CategoryListView.as_view(),
        name="category-list"
    ),
    path(
        "categories/create/",
        views.CategoryCreateView.as_view(),
        name="category-create"
    ),
    path(
        "categories/<int:pk>/update/",
        views.CategoryUpdateView.as_view(),
        name="category-update"
    ),
    path(
        "categories/<int:pk>/delete/",
        views.CategoryDeleteView.as_view(),
        name="category-delete"),

    path(
        "warehouses/",
        views.WarehouseListView.as_view(),
        name="warehouse-list"),
    path(
        "warehouses/create/",
        views.WarehouseCreateView.as_view(),
        name="warehouse-create"),
    path(
        "warehouses/<int:pk>/update/",
        views.WarehouseUpdateView.as_view(),
        name="warehouse-update"),
    path(
        "warehouses/<int:pk>/delete/",
        views.WarehouseDeleteView.as_view(),
        name="warehouse-delete"),
    path(
        "materials/<int:material_pk>/offers/save/",
        views.offer_save,
        name="offer-save"
    ),
    path(
        "materials/<int:material_pk>/offers/<int:supplier_pk>/delete/",
        views.offer_delete,
        name="offer-delete"
    ),
    path(
        "catalog/",
        views.PublicMaterialListView.as_view(),
        name="public-material-list",
    ),
    path(
        "catalog/<int:pk>/",
        views.PublicMaterialDetailView.as_view(),
        name="public-material-detail",
    ),
    path(
        "delivery/",
        views.DeliveryView.as_view(),
        name="delivery",
    ),
    path(
        "contacts/",
        views.ContactsView.as_view(),
        name="contacts",
    ),
]
